language: node_js
cache:
  directories:
  - node_modules
  - "~/.npm"
node_js:
- '12'
git:
  depth: 3
script:
- yarn test
notifications:
  slack:
    secure: eWVg99EsjvCvgtR8VSYohV9sIMbn5Q2/OTlN7CoeVwn3QCyqI2ulnlh/h3Hi8Gyoui3mDIUhpi281urvEPXYm+oPZVwqkH5S29qzC0Vjb16A4G2YaNGGr8BaTjuVFOpigtFZzs/duc3zdCem6APRaWV+8pmmrMQDN56Wp2pXepGKkNyxFiNGvDQfdTxmqi4OHv89hSRVsi1QRuCQCJMA/N9/VIDmaUSmjm+7vNpaE/ZTLwdTttuxGT/BxSm0CfercMT9lfqZEfcBPEbBNch8gbsoTzONcRELjkBB57Xl4RBlE+f1N+5Az34nTFVZhr/qoXC0v/7x1+QdIixT8IThGKXNnsCS2l3treZwk4jfsCFOuabuO+WnXyfoP8EOgmX8ddW3LwJZDQuLKfmo92RXYbc4PLZW1yHUEZX1VQOgpEfhMiCXowSXjhhnWub91qUXQCCFqdYjaOC6VcaylBQkNowjTVNYm5goy8t2NgFUE8hmDjV97eZlXNspWNoFCwUPvzWXtfDqO2/Nfkl3cVpC4V9QhLRlmxTOHD2KDm91qmQ+h9NNkz06a+EC5UMgPrID+ExSpl4JKT81JUxl0RJw1kVrGNNuV/1wPIXJtrsmLdFneHGmejZpIGcJnoyH1OR6shbLexinj6fwYHoeOaVfHXYYp34OTtCdoBFnztmjmfw=
  email:
    recipients:
    - uztarizjorge@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  cleanup: false
  keep-history: true
  api_key:
    secure: qIYaMhLnt5EsR7g4T9Pfj/n4snbr1G30qCNFt24ClZqXJmGsq0DXTYrUOG6gyk9e2VC3WnZIneDvqWHXTYu+F43QyYeziXGmLQ6pYf6pXQdkJyQbLQJ9dNUBidKfjMEBdZ3foXx8/A3icLyovJvcuHfG7SQyjXxNTsy2UI8J73t+rvEhtEW3hPEvKaAq6kRYwsP7FexE+9n5S8byTNb6ghPCVADcmhVEnZTPL1QlB87h7UwqsxgURIP9btCHBpuna+0QmXqYwDTzFO7zD+kvAvzI8Boc200+dWrNFX6eqdhSUo3gaJxrAsx5xKxDZHjR28/xM/9sNFcbO5lJG0pCyEUjEQXRLh+wFtfVeaioNqk6cMNxtZmuT3Ht2r6Ih7WDQf8OZZk39WGgnDh8ueeRqO0cgkTI2rIhF/q8w+V8D8YPbdzRHDqk/qorhCAluy6WG2aQNe1yjxl4nTFHUnE49xhAFDJA3L1AZMYWYjDwca3LIam+pMBjulNoMXEVoYydsswmzfD4Ttyz2spEzmrQxJLbxtsxAT2enEDhNNjxBTeq1d/IzzYOXf3bugUAs4zzWDrMQDn8lfmJCDM7G/3RkK+aPVWgSbpuYUM7XYmXvDuifSp38L6nQ3+HHSjucl4BGNDeXCk5R7YzNgCF9+2+uO/rr/wu+mgasuQGJuDfiDc=
  app: platzi-store-backend1
  on:
    repo: lamborg1987/platzi-store-backend
