language: node_js
cache:
  directories:
  - node_modules
  - "~/.npm"
node_js:
- '12'
git:
  depth: 3
script:
- yarn test
notifications:
  slack:
    secure: DGOnEb00RKVtFgfFyIMnszJGaKNsm+YcOGw0H6brYFWYK4Ys7poiu1zW/rUlKOgnOPifkOQ3yjG6zHHKWEZoWBKl04jlLfGo+XJtU6v8SVRPCKx3CtVGs5hpXXAwHqCeMMlwyNbx5xS5jYKfpCEc6sZBGqEDgIhD2gVAxjd7R2Gv05iJ5Q3Ra9wgkpRrLt4IhTmwRlDIfjRsfyh5DIFm0s7MiMNMukDjgbEVdHYyLq2GQJt5XTbsi502huUsRtFcle4KDsSPRc/rOnWXAFehL9Aa3W3bF3rrBuGYBGj27ZHxDYcsWI6s9ZcPJoOKZzoM9ReqYPHfiAiG029mjiST474WskgWC95KIRObpIF61tkf/BrgJwzKvEm9iMmeLn2VtiMorYtrS6eQF1aq5WZjus/A005S+LPd7CzjZiLX+tmeHTaPs5Buw8TUJudyo0NQcLY+6Y0o5O1n3jQMVCfc3D/Lb/AFj2zb0xonNGLxK7+/0OQflrW5sF8nn17SZfEWwAOBL68uXo/UNtHiBocRato1AjlI54QUIQ1LHfRrSn7cMGsjYqY5oDRIVs/n2uLLgcNFFhhjaGeF6my0a6wImeIgP/iyd9uDzSdI/ilT1jlZ315+3edJJHlF8yIDRfGXBAM73DmN9jqo6WJ9x3Ih1AZ2T5l+4PN07USQj5daEFQ=
  email:
    recipients:
    - uztarizjorge@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  cleanup: false
  keep-history: true
  api_key:
    secure: qIYaMhLnt5EsR7g4T9Pfj/n4snbr1G30qCNFt24ClZqXJmGsq0DXTYrUOG6gyk9e2VC3WnZIneDvqWHXTYu+F43QyYeziXGmLQ6pYf6pXQdkJyQbLQJ9dNUBidKfjMEBdZ3foXx8/A3icLyovJvcuHfG7SQyjXxNTsy2UI8J73t+rvEhtEW3hPEvKaAq6kRYwsP7FexE+9n5S8byTNb6ghPCVADcmhVEnZTPL1QlB87h7UwqsxgURIP9btCHBpuna+0QmXqYwDTzFO7zD+kvAvzI8Boc200+dWrNFX6eqdhSUo3gaJxrAsx5xKxDZHjR28/xM/9sNFcbO5lJG0pCyEUjEQXRLh+wFtfVeaioNqk6cMNxtZmuT3Ht2r6Ih7WDQf8OZZk39WGgnDh8ueeRqO0cgkTI2rIhF/q8w+V8D8YPbdzRHDqk/qorhCAluy6WG2aQNe1yjxl4nTFHUnE49xhAFDJA3L1AZMYWYjDwca3LIam+pMBjulNoMXEVoYydsswmzfD4Ttyz2spEzmrQxJLbxtsxAT2enEDhNNjxBTeq1d/IzzYOXf3bugUAs4zzWDrMQDn8lfmJCDM7G/3RkK+aPVWgSbpuYUM7XYmXvDuifSp38L6nQ3+HHSjucl4BGNDeXCk5R7YzNgCF9+2+uO/rr/wu+mgasuQGJuDfiDc=
  app: platzi-store-backend1
  on:
    repo: lamborg1987/platzi-store-backend
