language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn test

notifications:
  slack: dbascmconsis:OGMNp9zTyCRkYTY5tskK3Mjc
    on_success: always
    on_failure: always

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 5e9abf33-f60c-4276-93a4-0cd290fe3ff1
  app: platzi-store-backend1
  on:
    repo: lamborg1987/platzi-store-backend
